import fs from 'fs';
import path from 'path';
import puppeteer, { type Browser } from 'puppeteer';
import { Marked, type Tokens } from 'marked';

// Deterministic, local markdown -> PDF conversion. Runs entirely in this process (headless
// Chromium + mermaid.js), no LLM call involved - the report text has already been generated by
// the time this runs, so this only ever transforms text that already exists.

let browserPromise: Promise<Browser> | undefined;

function getBrowser(): Promise<Browser> {
  if (!browserPromise) {
    browserPromise = puppeteer.launch({
      headless: true,
      // Only ever renders our own already-generated markdown/mermaid content (no external
      // navigation), so the sandbox isn't protecting against untrusted input here; disabling it
      // avoids "No usable sandbox" failures on hosts without user-namespace support.
      args: ['--no-sandbox', '--disable-setuid-sandbox']
    });
  }
  return browserPromise;
}

let mermaidBundleCache: string | undefined;

function loadMermaidBundle(): string {
  if (!mermaidBundleCache) {
    mermaidBundleCache = fs.readFileSync(
      path.join(process.cwd(), 'node_modules', 'mermaid', 'dist', 'mermaid.min.js'),
      'utf-8'
    );
  }
  return mermaidBundleCache;
}

function escapeHtml(input: string): string {
  return input
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function markdownToHtml(markdown: string): string {
  const instance = new Marked({ gfm: true, breaks: false });
  instance.use({
    renderer: {
      code({ text, lang }: Tokens.Code): string {
        if ((lang || '').trim().toLowerCase() === 'mermaid') {
          return `<pre class="mermaid">${escapeHtml(text)}</pre>`;
        }
        const langName = (lang || '').match(/^\S*/)?.[0] ?? '';
        const langClass = langName ? ` class="language-${escapeHtml(langName)}"` : '';
        return `<pre><code${langClass}>${escapeHtml(text)}</code></pre>\n`;
      }
    }
  });
  return instance.parse(markdown) as string;
}

const DOCUMENT_CSS = `
  :root { color-scheme: light; }
  * { box-sizing: border-box; }
  body {
    margin: 0;
    font-family: -apple-system, 'Segoe UI', Helvetica, Arial, sans-serif;
    color: #1e293b;
    font-size: 11.5px;
    line-height: 1.6;
  }
  .cover {
    padding: 8mm 0 10mm;
    margin-bottom: 8mm;
    border-bottom: 3px solid #4f46e5;
  }
  .cover .eyebrow {
    font-size: 9px;
    font-weight: 700;
    letter-spacing: 0.12em;
    text-transform: uppercase;
    color: #4f46e5;
    margin-bottom: 4px;
  }
  .cover h1 { font-size: 22px; margin: 0 0 6px; color: #0f172a; }
  .cover .meta { font-size: 9.5px; color: #64748b; }
  h1, h2, h3, h4 { color: #0f172a; font-weight: 700; page-break-after: avoid; }
  h2 {
    font-size: 15px;
    margin-top: 22px;
    padding-bottom: 4px;
    border-bottom: 1.5px solid #e2e8f0;
  }
  h3 { font-size: 13px; margin-top: 16px; }
  p { margin: 6px 0; }
  a { color: #4338ca; }
  ul, ol { padding-left: 20px; }
  li { margin: 3px 0; }
  blockquote {
    margin: 10px 0;
    padding: 6px 12px;
    border-left: 3px solid #a5b4fc;
    background: #f5f5ff;
    color: #4338ca;
  }
  table {
    border-collapse: collapse;
    width: 100%;
    margin: 10px 0;
    font-size: 10px;
    page-break-inside: avoid;
  }
  th, td { border: 1px solid #e2e8f0; padding: 5px 8px; text-align: left; vertical-align: top; }
  th { background: #eef2ff; color: #312e81; font-weight: 700; }
  tr:nth-child(even) td { background: #f8fafc; }
  code {
    font-family: 'SFMono-Regular', Consolas, Menlo, monospace;
    background: #f1f5f9;
    padding: 1px 4px;
    border-radius: 3px;
    font-size: 10px;
  }
  pre {
    background: #0f172a;
    color: #e2e8f0;
    padding: 10px 12px;
    border-radius: 6px;
    overflow: hidden;
    page-break-inside: avoid;
  }
  pre code { background: none; padding: 0; color: inherit; }
  .mermaid {
    background: #ffffff;
    border: 1px solid #e2e8f0;
    border-radius: 8px;
    padding: 12px;
    margin: 12px 0;
    text-align: center;
    page-break-inside: avoid;
  }
  .mermaid svg { max-width: 100%; height: auto; }
  hr { border: none; border-top: 1px solid #e2e8f0; margin: 16px 0; }
`;

const MERMAID_INIT_SCRIPT = `
  window.mermaid.initialize({
    startOnLoad: false,
    theme: 'base',
    securityLevel: 'strict',
    themeVariables: {
      primaryColor: '#eef2ff',
      primaryTextColor: '#312e81',
      primaryBorderColor: '#6366f1',
      lineColor: '#6366f1',
      secondaryColor: '#f8fafc',
      tertiaryColor: '#ffffff',
      fontFamily: '-apple-system, Segoe UI, Helvetica, Arial, sans-serif',
      fontSize: '13px'
    },
    flowchart: { curve: 'basis', htmlLabels: true },
    sequence: { actorFontSize: 12, messageFontSize: 12 }
  });
`;

function buildHtmlDocument(bodyHtml: string, title: string): string {
  const generatedAt = new Date().toLocaleString('en-US', {
    dateStyle: 'long',
    timeStyle: 'short'
  });

  return `<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>${escapeHtml(title)}</title>
<style>${DOCUMENT_CSS}</style>
</head>
<body>
  <div class="cover">
    <div class="eyebrow">NexusAgent Research Network &middot; Synthesized Report</div>
    <h1>${escapeHtml(title)}</h1>
    <div class="meta">Compiled by Lead Orchestrator Dr. Astra &middot; Generated ${escapeHtml(generatedAt)}</div>
  </div>
  ${bodyHtml}
  <script>${loadMermaidBundle()}</script>
  <script>${MERMAID_INIT_SCRIPT}</script>
</body>
</html>`;
}

export interface PdfReportOptions {
  readonly markdown: string;
  readonly title?: string;
}

/**
 * Converts a completed markdown research report (including ```mermaid fenced diagrams) into a
 * paginated PDF with the diagrams rendered as real vector graphics (via mermaid.js running inside
 * headless Chromium), not left as raw text blocks.
 */
export async function renderMarkdownReportToPdf({ markdown, title }: PdfReportOptions): Promise<Buffer> {
  const bodyHtml = markdownToHtml(markdown);
  const html = buildHtmlDocument(bodyHtml, title || 'Synthesized Technical Research Report');

  const browser = await getBrowser();
  const page = await browser.newPage();
  try {
    await page.setContent(html, { waitUntil: 'load' });

    // suppressErrors so one malformed diagram (occasional LLM mermaid syntax slip) renders as an
    // inline error graphic instead of aborting the whole document.
    await page.evaluate(async () => {
      await (window as unknown as { mermaid: { run: (opts: unknown) => Promise<void> } }).mermaid.run({
        querySelector: '.mermaid',
        suppressErrors: true
      });
    });

    const pdf = await page.pdf({
      format: 'A4',
      printBackground: true,
      margin: { top: '18mm', bottom: '16mm', left: '16mm', right: '16mm' },
      displayHeaderFooter: true,
      headerTemplate: '<div></div>',
      footerTemplate: `<div style="width:100%;font-size:8px;color:#94a3b8;text-align:center;padding:0 16mm;font-family:Arial,sans-serif;">Page <span class="pageNumber"></span> of <span class="totalPages"></span> &middot; NexusAgent Research Network</div>`
    });

    return Buffer.from(pdf);
  } finally {
    await page.close();
  }
}
